### ISSUE TITLE
Gene-based annotations

### ISSUE THREAD

**Issue by schelhorn** [taunometsalu/ClustVis#1]
Great project! Is there any chance you'd be willing to add gene-based annotations, like for instance in the `heatplus` R package ([PDF, page 13](http://www.bioconductor.org/packages/release/bioc/vignettes/Heatplus/inst/doc/annHeatmap.pdf))? These annotation data could be added the same way in the input matrix as for the sample-based annotations, and also visualized identically (but on the Y axis). That would be of great value to highlight custom functional (e.g., pathway) groupings of genes, and see if they cluster well together.

**Comment by taunometsalu** [comment]
Thanks for the idea, it would indeed be useful to have this feature. Though, it needs some restructuring of the input file format and guessing annotation rows automatically will get more complex. I will try to add it by the end of July.
