### ISSUE TITLE
better examples when using straight from R

### ISSUE THREAD

**Issue by brobr** [taunometsalu/ClustVis#13]
Hi, thanks for ClustVis as a means for getting a PCA analysis of data. The web-interface for the heatmap, however, hangs too often when changing parameters to adapt clustering method, figure and label sizes. Could you maybe provide examples in the Vignette how to set/change these values in an R-script/command so that someone can produce/alter figures independent of server- or web capacity straight from the R command line?

**Comment by taunometsalu** [comment]
Hi brobr,

The functions used in the vignette are well documented in the package, you can just browse the standard R help pages to see how to modify the default settings:

```
library(clustvis)
?importData
?processData
?generatePCA
?generateHeatmap
?exportData
```

These functions refer to the different tabs in the web interface, and the parameter names used in the functions are also similar to the web.

Does it help in your case? If you have some specific question, please let me know.

**Comment by brobr** [comment]
Ah, yes; thanks for the pointer (bit of a novice to R)
