### ISSUE TITLE
clustvis

### ISSUE THREAD

**Issue by mocherry** [taunometsalu/ClustVis#14]
Dear Clustvis developer,

while I like the Web-version of Clustvis a lot, I often encounter problems with the server crashing or being unresponsive.
Trying to use the Docker Version does not work for me either. I am using Windows10.
Now, I have installed the R version, which works with the example provided. However, I could not find any documentation describing how to pass all the different parameters to the pipeline to customize the heatmaps.

Help would be appreciated.

Thanks
Matthias

**Comment by taunometsalu** [comment]
Hi mocherry,

The documentation is available using R native ?function interface, see https://github.com/taunometsalu/ClustVis/issues/13

Let me know if something is missing from there.
