### ISSUE TITLE
Command line or api-like automation?

### ISSUE THREAD

**Issue by xguse** [taunometsalu/ClustVis#4]
Hello and THANK YOU for gluing these tools together!

I was wondering whether there exists a way to automate the tool? I know that I can put my own pipeline together that use these tools, but that would be kind of a waste seeing as that is basically what you have here.  I was just wondering if one could or has implemented a way besides filling in a web form every time to configure and submit files to clustvis.  I hope that I haven't just missed this in your documentation.

Thanks again!

**Comment by taunometsalu** [comment]
Thanks, good idea! There is no official API at the moment, but you can check the source file [global.R](https://github.com/taunometsalu/ClustVis/blob/master/global.R) and try to run the functions `plotPCA` and `plotHeatmap` separately. The variable `data$inputSaved` contains all parameters that are given to the functions.

**Comment by taunometsalu** [comment]
Just to let you know that I am in the process of refactoring the code, it is not yet made into a package (no documentation yet etc.), but you can try it out and let me know if you have any comments. You can use something like this to generate the plots:

```
source("https://raw.githubusercontent.com/taunometsalu/ClustVis/master/global_package.R")
d = importData("~/Downloads/0_myfile.csv")
proc = processData(d)

#pca:
pca = generatePCA(proc)
savePCA(pca, file = "~/Downloads/0_pca.pdf")

#hm:
hm = generateHeatmap(proc)
saveHeatmap(hm, file = "~/Downloads/0_hm.pdf")
```

**Comment by taunometsalu** [comment]
The code is now built into a proper R package, see title page of this repo for details.
