### ISSUE TITLE
http://biit.cs.ut.ee/clustvis/ not working

### ISSUE THREAD

**Issue by Kgirija** [taunometsalu/ClustVis#7]
Hi, I am trying to access clustvis tool (http://biit.cs.ut.ee/clustvis/) but its not working. It opens the web page but no  further process happening.

I used it many times earlier and its a very useful for my study, but now its not working.

Do there is any maintenance issue? 

Please help me, I need it urgently.

Best regards

**Comment by taunometsalu** [comment]
Sorry for late answer. There was a performance issue with many concurrent users. Can you please try again, it should be working now.

**Comment by NeonatalResearcher** [comment]
I'm having the same issue with Clustviz. Having been trying most days recently and the page loads but then seems to crash and I can't upload any data. 
Is this likely to be resolved?

**Comment by taunometsalu** [comment]
We have got similar reports from multiple users, but so far we don't know what exactly causes the issue. Some users have got it working with another computer or browser.

We are also planning a server configuration change during next weeks which will make the websocket connection more stable. It may solve the problem.

**Comment by taunometsalu** [comment]
We made a major configuration change to the server, please check whether it is working for you now.
