### ISSUE TITLE
Disconnect from the server after uploading

### ISSUE THREAD

**Issue by deschan05** [taunometsalu/ClustVis#9]
Hi there,

first of all thanks for sharing this platform and your knowlegde of course! 
Either I use the normal or large editon tool, I keep getting disconnected after uploading my csv or tab files. I also tried to copy-paste it without success.  I look Forward to your advice!
Thanks,
Dejan

**Comment by deschan05** [comment]
soo... i just found out that the format of my numbers should numeric and not scientific....

**Comment by taunometsalu** [comment]
Probably, there is also a bug in the processing code, it should never crash like this, but rather show an empty dataset.

Can you please send your data or a minimal reproducible example (you can use my e-mail taunometsalu [at] gmail [dot] com if you don't want to share it publicly).
